// Code generated by protoc-gen-go.
// source: state.proto
// DO NOT EDIT!

/*
Package membership is a generated protocol buffer package.

It is generated from these files:
	state.proto

It has these top-level messages:
	HeartBeatState
	EndPointState
*/
package membership

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type HeartBeatState struct {
	Generation uint32 `protobuf:"varint,1,opt,name=generation" json:"generation,omitempty"`
	Version    uint32 `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
}

func (m *HeartBeatState) Reset()         { *m = HeartBeatState{} }
func (m *HeartBeatState) String() string { return proto.CompactTextString(m) }
func (*HeartBeatState) ProtoMessage()    {}

type EndPointState struct {
	Hbstate *HeartBeatState `protobuf:"bytes,1,opt,name=hbstate" json:"hbstate,omitempty"`
}

func (m *EndPointState) Reset()         { *m = EndPointState{} }
func (m *EndPointState) String() string { return proto.CompactTextString(m) }
func (*EndPointState) ProtoMessage()    {}

func (m *EndPointState) GetHbstate() *HeartBeatState {
	if m != nil {
		return m.Hbstate
	}
	return nil
}
